fix: node parameter fallback

diff --git a/composer b/composer
--- a/composer
+++ b/composer
@@ -9,7 +9,7 @@ echo === Setup $me ===
 
 if ! testc composer; then
 	if ! testc php; then
-		>&2 echo "$me: Composer requires PHP. Aborting."
+		echo "$me: Composer requires PHP. Aborting." >&2
 		return 1
 	fi
 	tmp=$(mktemp)
diff --git a/lemp b/lemp
--- a/lemp
+++ b/lemp
@@ -8,7 +8,7 @@ echo ''
 echo === Setup $me ===
 phpversion=$1
 
-test -n "$phpversion" || { >&2 echo "$me: Parameter 1 is missing: phpversion"; exit 1; } 
+test -n "$phpversion" || { echo "$me: Parameter 1 is missing: phpversion" >&2; exit 1; } 
 
 if ! testc nginx; then
 	pkgreq nginx
