fix: fallback variables

diff --git a/lemp b/lemp
--- a/lemp
+++ b/lemp
@@ -8,7 +8,7 @@ echo ''
 echo === Setup $me ===
 phpversion=$1
 
-[ -n "$phpversion" ] || { >&2 echo "$me: Parameter 1 is missing: phpversion"; exit 1; } 
+test -n "$phpversion" || { >&2 echo "$me: Parameter 1 is missing: phpversion"; exit 1; } 
 
 if ! testc nginx; then
 	pkgreq nginx
diff --git a/node b/node
--- a/node
+++ b/node
@@ -8,7 +8,7 @@ echo ''
 echo === Setup $me ===
 majorversion=$1
 
-[ -n "$majorversion" ] || { >&2 echo "$me: Parameter 1 is missing: majorversion"; exit 1; } 
+test -n "$majorversion" || { >&2 echo "$me: Parameter 1 is missing: majorversion"; exit 1; } 
 
 if ! testc nvm; then
 	pkgreq curl
