fix: node installer on Alpine

diff --git a/node b/node
--- a/node
+++ b/node
@@ -8,16 +8,19 @@ echo ''
 echo === Setup $me ===
 majorversion=${1-lts}
 
-test -n "$majorversion" || { >&2 echo "$me: Parameter 1 is missing: majorversion"; exit 1; } 
+test -n "$majorversion" || { echo "$me: Parameter 1 is missing: majorversion" >&2; exit 1; } 
 
 if ! testc node; then
 	if [ "$ENV_DIST_NAME" = "alpine" ]; then
 		# Alpine will not support node binaries supplied by nvm, so falling back to apk
 		if [ "$majorversion" = "lts" ]; then
-			pkgreq nodejs
+			pkgreq nodejs npm
 		else
 			pkgreq nodejs~=$majorversion
+			read npmv < <(echo $(node -e "fetch('https://nodejs.org/dist/index.json').then(r=>r.json()).then(e=>console.info(e.filter(a=>a.version=='$(node -v)')[0].npm))"))
+			pkgreq npm~=$npmv
 		fi
+		npm i npx pm2 -g
 	else
 		if ! testc nvm; then
 			pkgreq curl bash
@@ -57,10 +60,9 @@ sourcerc
 			nvm alias default $majorversion
 		fi
 	fi
-fi
-
-if ! testc pm2; then
-	npm i pm2 -g
+	if ! testc pm2; then
+		npm i pm2 -g
+	fi
 fi
 
 set -e
